implement "usage"
Need some fixes:
- Hide exit code in Cluster Mode
- Clean Logfile make a double output of exit code
- run script without commands

diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,16 +1,16 @@
 #!/bin/bash
 
-#Variable / Function
+# Variable / Function
 LOG_FILE=/var/log/update-$HOSTNAME.log    # <- change location for logfile if you want
-VERSION=3.0
+VERSION=3.1
 
-#Colors
+# Colors
 BL='\033[36m'
 RD='\033[01;31m'
 GN='\033[1;92m'
 CL='\033[m'
 
-#Header
+# Header
 function HEADER_INFO {
   clear
   echo -e "\n \
@@ -31,69 +31,72 @@ EOF
   echo -e "\n \
            *** Version:  $VERSION  *** \n \
            *** Mode: $MODE ***"
-  if [[ $HEADLESS == "1" ]]; then
+  if [[ "$HEADLESS" == true ]]; then
     echo -e "            ***    Headless    ***"
   else
-    if [[ $UPDATE != "1" ]]; then
     echo -e "            ***  Interactive   ***"
-    fi
   fi
   CHECK_ROOT
 }
 
-#Update Options
-while getopts 123xhu opt 2>/dev/null
-do
-  case $opt in
-    1) CLUSTER_MODE=1;;
-    2) HOST_MODE=1;;
-    3) HEADLESS=1;;
-    x) RICM=1;; # Run In Cluster Mode
-    u) UPDATE=1;;
-    h) echo -e "\nOptions: \
-                \n======== \
-                \n-1   Cluster Mode (Automatic - No need to set) \
-                \n-2   Host Mode \
-                \n-3   Headless \
-                \n-u   Update Proxmox-Updater\n"
-       exit 1;;
-    ?) echo -e "Wrong option! (-h for Help)"
-       exit 1
-  esac
-done
-
-#Check root
+# Check root
 function CHECK_ROOT() {
-  if [[ $RICM != "1" && $EUID -ne 0 ]]; then
+  if [[ "$RICM" != true && $EUID -ne 0 ]]; then
       echo -e "\n ${RD}--- Please run this as root ---${CL}\n"
-      exit 0
+      exit 2
   fi
 }
 
-#Check Cluster Mode
-if [ -f "/etc/corosync/corosync.conf" ]; then
-  HOSTS=$(awk '/ring0_addr/{print $2}' "/etc/corosync/corosync.conf")
-fi
+function USAGE {
+  if [ "$HEADLESS" != true ]; then
+      echo -e "\nUsage: $0 [OPTIONS...] {COMMAND}\n"
+      echo -e "Manages the Proxmox-Updater."
+      echo -e "  -h --help            Show this help"
+      echo -e "  -s --silent          Silent / Headless Mode\n"
+      echo -e "Commands:"
+      echo -e "  host                 Host-Mode"
+      echo -e "  cluster              Cluster-Mode"
+      echo -e "  update               Update Proxmox-Updater"
+      echo -e "  uninstall            Uninstall Proxmox-Updater\n"
+      echo -e "Report issues at: <https://github.com/BassT23/Proxmox/issues>\n"
+  fi
+}
 
-#Host Update
+function UPDATE(){
+  bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/master/install.sh) update
+  exit 2
+}
+
+function UNINSTALL(){
+  echo -e "\n${BL}[Info]${GN} Uninstall Proxmox-Updater${CL}\n"
+  echo -e "${RD}Really want to remove Proxmox-Updater?${CL}"
+  read -p "Type [Y/y] for yes - enything else will exit " -n 1 -r
+  if [[ $REPLY =~ ^[Yy]$ ]]; then
+    bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/master/install.sh) uninstall
+  else
+    exit 2
+  fi
+}
+
+# Host Update
 function UPDATE_HOST() {
   HOST=$1
   echo -e "\n${BL}[Info]${GN} Updating${CL} : ${GN}$HOST${CL}"
-  if [[ $HEADLESS == "1" ]]; then
-    ssh "$HOST" 'bash -s' < "$0" -- -23x
+  if [[ "$HEADLESS" == true ]]; then
+    ssh "$HOST" 'bash -s' < "$0" -- "-s -c host"
   else
-    ssh "$HOST" 'bash -s' < "$0" -- -2x
+    ssh "$HOST" 'bash -s' < "$0" -- "-c host"
   fi
 }
 
-#Host Update Start
+# Host Update Start
 function HOST_UPDATE_START() {
   for HOST in $HOSTS; do
     UPDATE_HOST "$HOST"
   done
 }
 
-#Container Update
+# Container Update
 function UPDATE_CONTAINER() {
   CONTAINER=$1
   NAME=$(pct exec "$CONTAINER" hostname)
@@ -103,7 +106,7 @@ function UPDATE_CONTAINER() {
   case "$os" in
     "ubuntu" | "debian" | "devuan")
       pct exec "$CONTAINER" -- bash -c "echo -e --- APT UPDATE --- && apt-get update && echo"
-      if [[ $HEADLESS == "1" ]]; then
+      if [[ "$HEADLESS" == true ]]; then
         pct exec "$CONTAINER" -- bash -c "echo -e --- APT UPGRADE HEADLESS --- && \
                                           DEBIAN_FRONTEND=noninteractive apt-get -o APT::Get::Always-Include-Phased-Updates=true dist-upgrade -y && \
                                           DEBIAN_FRONTEND=noninteractive apt-get full-upgrade -y && echo"
@@ -127,7 +130,7 @@ function UPDATE_CONTAINER() {
   esac
 }
 
-#Container Update Start
+# Container Update Start
 function CONTAINER_UPDATE_START() {
   # Get the list of containers
   CONTAINERS=$(pct list | tail -n +2 | cut -f1 -d' ')
@@ -153,7 +156,7 @@ function CONTAINER_UPDATE_START() {
 
 function UPDATE_HOST_ITSELF() {
   echo -e "\n--- APT UPDATE ---" && apt-get update
-  if [[ $HEADLESS == "1" ]]; then
+  if [[ "$HEADLESS" == true ]]; then
     echo -e "\n--- APT UPGRADE HEADLESS ---" && \
             DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
   else
@@ -165,12 +168,12 @@ function UPDATE_HOST_ITSELF() {
 }
 
 # Logging
-if [[ $RICM != "1" ]]; then
+if [[ "$RICM" != true ]]; then
   touch "$LOG_FILE"
   exec &> >(tee "$LOG_FILE")
 fi
 function CLEAN_LOGFILE() {
-  if [[ $RICM != "1" ]]; then
+  if [[ "$RICM" != true ]]; then
     tail -n +2 "$LOG_FILE" > tmp.log && mv tmp.log "$LOG_FILE"
     cat $LOG_FILE | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,3})*)?[mGK]//g" | tee "$LOG_FILE"
     chmod 640 "$LOG_FILE"
@@ -180,12 +183,14 @@ function CLEAN_LOGFILE() {
   fi
 }
 
-# Error/Exit
-set -e
 function EXIT() {
   EXIT_CODE=$?
+  # Exit direct
+  if [[ $EXIT_CODE == 2 ]]; then
+#    CLEAN_LOGFILE
+    exit
   # Update Finish
-  if [[ $EXIT_CODE = "0" ]]; then
+  elif [[ $EXIT_CODE == 0 ]]; then
     echo -e "${GN}Finished, All Containers Updated.${CL}\n"
     /root/Proxmox-Update-Scripts/exit/passed.sh
   # Update Error
@@ -193,39 +198,90 @@ function EXIT() {
     echo -e "${RD}Error during Update --- Exit Code: $EXIT_CODE${CL}\n"
     /root/Proxmox-Update-Scripts/exit/error.sh
   fi
-  CLEAN_LOGFILE
+#  CLEAN_LOGFILE
 }
 
 # Exit Code
-if [[ $RICM != "1" && $UPDATE != "1" ]]; then
+set -e
+if [[ "$RICM" != true ]]; then
   trap EXIT EXIT
 fi
 
-#Update Proxmox-Updater
-if [[ $UPDATE == "1" ]]; then
-  MODE=" Update "
-  HEADER_INFO
-  echo -e "\n${BL}[Info]${GN} Updating script ...${CL}\n"
-  bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/master/install.sh) update
-  exit 0
+_command=false
+
+# Check Cluster Mode
+if [ -f "/etc/corosync/corosync.conf" ]; then
+  HOSTS=$(awk '/ring0_addr/{print $2}' "/etc/corosync/corosync.conf")
 fi
 
-#Update Start
+# Update Start
 export TERM=xterm-256color
-if [[ -f /etc/corosync/corosync.conf && $HOST_MODE != "1" ]]; then
-  MODE=" Cluster"
-  HEADER_INFO
-  HOST_UPDATE_START
-  exit 0
-else
-  if [[ $RICM != "1" ]]; then
-    MODE="  Host  "
-    HEADER_INFO
-  fi
-    if [[ $RICM != "1" ]]; then
-      echo -e "\n${BL}[Info]${GN} Updating${CL} : ${GN}$HOSTNAME${CL}"
-    fi
-  UPDATE_HOST_ITSELF
-  CONTAINER_UPDATE_START
-  exit 0
-fi
+
+#if [ "$_command" = false ]; then
+#  ssh "$HOST" 'bash -s' < "$0" -- -c host
+#fi
+
+parse_cli()
+{
+  while test $# -gt -0
+  do
+    _key="$1"
+    case "$_key" in
+      -h|--help)
+        USAGE
+        exit 2
+        ;;
+      -s|--silent)
+        HEADLESS=true
+        ;;
+      -c)
+        RICM=true
+        ;;
+      host)
+        if [ "$_command" = false ]; then
+          _command=true
+          if [[ "$RICM" != true ]]; then
+            MODE="  Host  "
+            HEADER_INFO
+          fi
+            if [[ "$RICM" != true ]]; then
+            echo -e "\n${BL}[Info]${GN} Updating${CL} : ${GN}$HOSTNAME${CL}"
+            fi
+          UPDATE_HOST_ITSELF
+          CONTAINER_UPDATE_START
+        fi
+        ;;
+      cluster)
+        if [ "$_command" = false ]; then
+          _command=true
+          if [[ -f /etc/corosync/corosync.conf && $HOST_MODE != "1" ]]; then
+            MODE=" Cluster"
+            HEADER_INFO
+            HOST_UPDATE_START
+          fi
+        fi
+        ;;
+      uninstall)
+        if [ "$_command" = false ]; then
+          _command=true
+          UNINSTALL
+          exit 0
+        fi
+        ;;
+      update)
+        if [ "$_command" = false ]; then
+          _command=true
+          UPDATE
+          exit 0
+        fi
+        ;;
+      *)
+        echo -e "${RD}Error: Got an unexpected argument \"$_key\"${CL}";
+        USAGE;
+        exit 2;
+        ;;
+    esac
+    shift
+  done
+}
+parse_cli "$@"
