Update update

diff --git a/update b/update
--- a/update
+++ b/update
@@ -4,7 +4,7 @@
 LOG_FILE=/var/log/update-$HOSTNAME.log    # <- change location for logfile if you want
 
 #General
-VERSION=2.6
+VERSION=2.7
 
 #Header Cluster Mode
 function HEADER_INFO {
@@ -32,6 +32,7 @@ EOF
   else
     echo -e "            ***  Interactive   ***"
   fi
+  CHECK_ROOT
 }
 
 #Colors
@@ -42,7 +43,7 @@ CM='\xE2\x9C\x94\033'
 GN='\033[1;92m'
 CL='\033[m'
 
-#Update with Extras
+#Update Options
 while getopts 123xhu opt 2>/dev/null
 do
   case $opt in
@@ -63,7 +64,27 @@ do
   esac
 done
 
-#Update Proxmox Script
+#Check root
+function CHECK_ROOT() {
+  if [[ "$RICM" != "1" ]]; then
+    if [[ $EUID -eq 0 ]];then
+      echo -e "\n--- You are root ---"
+    else
+      echo -e "\n--- sudo will be used for the install ---"
+      #Check if it is actually installed
+      #If it isn't, exit because the install cannot complete
+      if [[ $(dpkg-query -s sudo) ]];then
+          export SUDO="sudo"
+          export SUDOE="sudo -E"
+      else
+          echo "--- Please install sudo or run this as root ---"
+          exit 1
+      fi
+    fi
+  fi
+}
+
+#Update Proxmox-Updater
 if [[ "$UPDATE" == "1" ]]; then
   MODE="  Update"
   HEADER_INFO
@@ -76,7 +97,7 @@ if [[ "$UPDATE" == "1" ]]; then
   chmod +x ./install.sh
   ./install.sh
   rm -R /root/Proxmox-Updater
-  printf "\n${GN}Proxmox-Updater - Updated${CL}\n\n"
+  echo -e "\n${GN}Proxmox-Updater - Updated${CL}\n"
   exit 0
 fi
 
@@ -102,22 +123,22 @@ function HOST_UPDATE_START() {
 #Container Update
 function UPDATE_CONTAINER() {
   CONTAINER=$1
-  NAME=`pct exec $CONTAINER hostname`
-  echo -e "${BL}[Info]${GN} Updating LXC ${BL}$CONTAINER${CL} : ${GN}$NAME${CL} \n"
+  NAME=$(pct exec "$CONTAINER" hostname)
+  echo -e "${BL}[Info]${GN} Updating LXC ${BL}$CONTAINER${CL} : ${GN}$NAME${CL}\n"
   pct config "$CONTAINER" > temp
-  os=`awk '/^ostype/' temp | cut -d' ' -f2`
+  os=$(awk '/^ostype/' temp | cut -d' ' -f2)
   if [ "$os" == "alpine" ]; then
         pct exec "$CONTAINER" -- bash -c "echo -e --- APK UPDATE --- && apk -U upgrade && echo"
   elif [ "$os" == "ubuntu" ] || [ "$os" == "debian" ] || [ "$os" == "devuan" ]; then
         pct exec "$CONTAINER" -- bash -c "echo -e --- APT UPDATE --- && apt-get update && echo"
         if [[ "$HEADLESS" == "1" ]]; then
-          pct exec "$CONTAINER" -- bash -c "echo -e --- APT UPGRADE --- && DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y"
-          pct exec "$CONTAINER" -- bash -c "DEBIAN_FRONTEND=noninteractive apt-get full-upgrade -y"
-          pct exec "$CONTAINER" -- bash -c "DEBIAN_FRONTEND=noninteractive apt-get -o APT::Get::Always-Include-Phased-Updates=true upgrade -y && echo"
+          pct exec "$CONTAINER" -- bash -c "echo -e --- APT UPGRADE --- && \
+                                            apt-get DEBIAN_FRONTEND=noninteractive -o APT::Get::Always-Include-Phased-Updates=true dist-upgrade -y \
+                                            apt-get DEBIAN_FRONTEND=noninteractive full-upgrade -y && echo"
         else
-          pct exec "$CONTAINER" -- bash -c "echo -e --- APT UPGRADE --- && apt-get dist-upgrade -y"
-          pct exec "$CONTAINER" -- bash -c "apt-get full-upgrade -y"
-          pct exec "$CONTAINER" -- bash -c "apt-get -o APT::Get::Always-Include-Phased-Updates=true upgrade -y && echo"
+          pct exec "$CONTAINER" -- bash -c "echo -e --- APT UPGRADE --- && \
+                                            apt-get -o APT::Get::Always-Include-Phased-Updates=true dist-upgrade -y && \
+                                            apt-get full-upgrade -y && echo"
         fi
         pct exec "$CONTAINER" -- bash -c "echo -e --- APT CLEANING --- && apt-get --purge autoremove -y"
         pct exec "$CONTAINER" -- bash -c "apt-get autoremove -y && echo"
@@ -130,6 +151,7 @@ function UPDATE_CONTAINER() {
   else
         pct exec "$CONTAINER" -- bash -c "echo -e --- YUM UPDATE --- && yum -y update && echo"
   fi
+  rm temp
 }
 
 #Container Update Start
@@ -138,12 +160,12 @@ function CONTAINER_UPDATE_START() {
   for CONTAINER in $CONTAINERS; do
     status=$(pct status "$CONTAINER")
     if [ "$status" == "status: stopped" ]; then
-      echo -e "${BL}[Info]${GN} Starting${BL} $CONTAINER ${CL} \n"
+      echo -e "${BL}[Info]${GN} Starting${BL} $CONTAINER ${CL}\n"
       pct start "$CONTAINER"
-      echo -e "${BL}[Info]${GN} Waiting For${BL} $CONTAINER${CL}${GN} To Start ${CL} \n"
+      echo -e "${BL}[Info]${GN} Waiting For${BL} $CONTAINER${CL}${GN} To Start ${CL}\n"
       sleep 5
       UPDATE_CONTAINER "$CONTAINER"
-      echo -e "${BL}[Info]${GN} Shutting down${BL} $CONTAINER ${CL} \n"
+      echo -e "${BL}[Info]${GN} Shutting down${BL} $CONTAINER ${CL}\n"
       pct shutdown "$CONTAINER" &
     elif [ "$status" == "status: running" ]; then
       UPDATE_CONTAINER "$CONTAINER"
@@ -152,7 +174,7 @@ function CONTAINER_UPDATE_START() {
   rm -rf temp
 }
 
-UPDATE_HOST_ITSELF() {
+function UPDATE_HOST_ITSELF() {
   echo -e "\n--- APT UPDATE ---" && apt-get update
   if [[ "$HEADLESS" == "1" ]]; then
     echo -e "\n--- APT UPGRADE ---" && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
@@ -181,12 +203,12 @@ function EXIT() {
   EXIT_CODE=$?
   # Update Finish
   if [[ "$EXIT_CODE" = "0" ]]; then
-    printf "${GN}Finished, All Containers Updated.${CL}\n\n"
+    echo -e "${GN}Finished, All Containers Updated.${CL}\n"
     CLEAN_LOGFILE
     /root/Proxmox-Update-Scripts/exit/passed.sh
   # Update Error
   else
-    printf "${RD}Error during Update --- Exit Code: $EXIT_CODE ${CL}\n\n"
+    echo -e "${RD}Error during Update --- Exit Code: $EXIT_CODE ${CL}\n"
     CLEAN_LOGFILE
     /root/Proxmox-Update-Scripts/exit/error.sh
   fi
